# Generated by Django 5.1.15 on 2026-02-17 10:13

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('role', models.CharField(choices=[('leadership', 'Leadership'), ('faculty', 'Faculty'), ('staff', 'Staff')], max_length=20)),
                ('job_title', models.CharField(max_length=200)),
                ('job_title_uz', models.CharField(blank=True, max_length=200)),
                ('job_title_ru', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='people/')),
                ('bio', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('bio_uz', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('bio_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='programs.department')),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['order', 'last_name'],
            },
        ),
    ]
