# Generated by Django 5.1.15 on 2026-04-06 09:46

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short intro shown by default'),
        ),
        migrations.AddField(
            model_name='person',
            name='excerpt_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='excerpt_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Full bio shown when "Find out more" is clicked'),
        ),
    ]
