# Generated by Django 5.1.15 on 2026-04-06 09:50

import apps.core.translation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_excerpt_person_excerpt_ru_person_excerpt_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(blank=True, max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('page', models.CharField(choices=[('leadership', 'Leadership Page (/about/leadership/)'), ('directory', 'Faculty Directory (/faculty/directory/)')], default='directory', help_text='Which page this role appears on', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
            bases=(apps.core.translation.TranslatedMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.role'),
        ),
    ]
