# Generated by Django 5.1.15 on 2026-04-06 09:54

import apps.core.translation
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_role_alter_person_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=200)),
                ('job_title_uz', models.CharField(blank=True, max_length=200)),
                ('job_title_ru', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='leadership/')),
                ('excerpt', models.TextField(blank=True, help_text='Short intro shown by default')),
                ('excerpt_uz', models.TextField(blank=True)),
                ('excerpt_ru', models.TextField(blank=True)),
                ('bio', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Full bio shown when "Find out more" is clicked')),
                ('bio_uz', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('bio_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Leader',
                'verbose_name_plural': 'Leadership',
                'ordering': ['order'],
            },
            bases=(apps.core.translation.TranslatedMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['order', 'last_name'], 'verbose_name': 'Faculty & Staff', 'verbose_name_plural': 'Faculty & Staff'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='person',
            name='excerpt_ru',
        ),
        migrations.RemoveField(
            model_name='person',
            name='excerpt_uz',
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
