# Generated by Django 5.1.15 on 2026-04-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_leader_remove_person_role_alter_person_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='email',
        ),
    ]
