# Generated by Django 5.1.15 on 2026-04-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_remove_leader_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='category',
            field=models.CharField(choices=[('rektorat', 'Rektorat'), ('departament', 'Departament')], default='rektorat', max_length=20),
        ),
    ]
