# Generated by Django 5.1.15 on 2026-02-17 10:10

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_uz', models.CharField(blank=True, max_length=300)),
                ('title_ru', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('description_uz', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('description_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='events/')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('caption_uz', models.CharField(blank=True, max_length=300)),
                ('caption_ru', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_uz', models.CharField(blank=True, max_length=300)),
                ('title_ru', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('excerpt_uz', models.TextField(blank=True)),
                ('excerpt_ru', models.TextField(blank=True)),
                ('body', django_ckeditor_5.fields.CKEditor5Field()),
                ('body_uz', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('body_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='news/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
