# Generated by Django 5.1.15 on 2026-02-20 12:35

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_uz', models.CharField(blank=True, max_length=300)),
                ('title_ru', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('excerpt_uz', models.TextField(blank=True)),
                ('excerpt_ru', models.TextField(blank=True)),
                ('body', django_ckeditor_5.fields.CKEditor5Field()),
                ('body_uz', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('body_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='press/')),
                ('category', models.CharField(blank=True, choices=[('partnerships', 'Partnerships'), ('academics', 'Academics'), ('institutional', 'Institutional'), ('events', 'Events'), ('accreditation', 'Accreditation'), ('student-success', 'Student Success')], max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
