# Generated by Django 4.2.26 on 2026-02-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newslettersubscriber_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
