# Generated by Django 5.1.15 on 2026-04-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_event_is_featured_event_is_top_newsarticle_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='excerpt_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='excerpt_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
