# Generated by Django 5.1.15 on 2026-04-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_event_excerpt_event_excerpt_ru_event_excerpt_uz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published_date'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('conference', 'Conference'), ('seminar', 'Seminar'), ('workshop', 'Workshop'), ('open-day', 'Open Day'), ('cultural', 'Cultural'), ('sports', 'Sports'), ('competition', 'Competition')], max_length=100),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(blank=True, choices=[('university', 'University'), ('academics', 'Academics'), ('research', 'Research'), ('international', 'International'), ('student-life', 'Student Life'), ('events', 'Events'), ('partnerships', 'Partnerships')], max_length=100),
        ),
    ]
