# Generated by Django 5.1.15 on 2026-04-02 11:30

import apps.core.translation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newsarticle_options_alter_event_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(blank=True, max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
            bases=(apps.core.translation.TranslatedMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='category',
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='events', to='news.category'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='news_articles', to='news.category'),
        ),
    ]
