# Generated by Django 5.1.15 on 2026-04-02 11:54

import apps.core.translation
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_category_remove_event_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_uz', models.CharField(blank=True, max_length=300)),
                ('title_ru', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('author', models.CharField(max_length=300)),
                ('author_type', models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student'), ('joint', 'Joint (Faculty & Student)')], default='faculty', max_length=20)),
                ('excerpt', models.TextField(blank=True)),
                ('excerpt_uz', models.TextField(blank=True)),
                ('excerpt_ru', models.TextField(blank=True)),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('body_uz', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('body_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='publications/')),
                ('external_url', models.URLField(blank=True, help_text='Link to external publication (journal, conference, etc.)')),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='publications', to='news.category')),
            ],
            options={
                'ordering': ['-published_date'],
            },
            bases=(apps.core.translation.TranslatedMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='PressRelease',
        ),
    ]
