# Generated by Django 5.1.15 on 2026-04-02 12:02

import apps.core.translation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_publication_delete_pressrelease'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(blank=True, max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(apps.core.translation.TranslatedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PublicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(blank=True, max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Publication Categories',
                'ordering': ['name'],
            },
            bases=(apps.core.translation.TranslatedMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.authortype'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='publications', to='news.publicationcategory'),
        ),
    ]
