# Generated by Django 5.1.15 on 2026-04-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_authortype_publicationcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='faculty',
            field=models.CharField(blank=True, choices=[('jurisprudence', 'Faculty of Jurisprudence'), ('business', 'Faculty of Business and Innovative Education')], max_length=50),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='faculty',
            field=models.CharField(blank=True, choices=[('jurisprudence', 'Faculty of Jurisprudence'), ('business', 'Faculty of Business and Innovative Education')], max_length=50),
        ),
    ]
