# Generated by Django 5.1.15 on 2026-04-09 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_event_faculty_newsarticle_faculty'),
        ('people', '0005_remove_leader_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='person',
            field=models.ForeignKey(blank=True, help_text='Link to a faculty member (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='people.person'),
        ),
    ]
