# Generated by Django 5.1.15 on 2026-04-16 11:44

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_publication_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
