# Generated by Django 5.1.15 on 2026-04-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_event_description_alter_newsarticle_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_ru',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='location_uz',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
