# Generated by Django 4.2.26 on 2026-02-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Google Analytics Measurement ID (e.g. G-XXXXXXXXXX)', max_length=30),
        ),
    ]
