# Generated by Django 4.2.26 on 2026-02-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_google_analytics_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('it', 'School of IT & Engineering'), ('business', 'School of Business & Economics'), ('law', 'School of Law'), ('humanities', 'School of Humanities & Social Sciences'), ('foundation', 'Foundation Programme'), ('admin', 'Administrative')], max_length=20)),
                ('department_label', models.CharField(blank=True, help_text='Display name for the department (e.g. "Information Technology Department"). Leave blank to use default.', max_length=100)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time')], max_length=20)),
                ('role', models.CharField(choices=[('academic', 'Academic'), ('staff', 'Staff')], max_length=20)),
                ('deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
    ]
