# Generated by Django 4.2.26 on 2026-02-21 15:10

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_jobposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique=True),
        ),
    ]
