# Generated by Django 4.2.26 on 2026-02-21 15:10

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    JobPosition = apps.get_model('core', 'JobPosition')
    for job in JobPosition.objects.filter(slug=''):
        base_slug = slugify(job.title)[:250] or 'position'
        slug = base_slug
        counter = 1
        while JobPosition.objects.filter(slug=slug).exists():
            slug = f'{base_slug}-{counter}'[:250]
            counter += 1
        job.slug = slug
        job.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobposition_description_jobposition_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
