# Generated by Django 4.2.26 on 2026-02-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_populate_job_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
