# Generated by Django 4.2.26 on 2026-02-21 15:15

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_jobposition_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('provider', models.CharField(default='Tashkent International University', max_length=200)),
                ('excerpt', models.TextField(help_text='Short description shown on the list page')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('level', models.CharField(choices=[('bachelor', "Bachelor's"), ('master', "Master's"), ('bachelor master', "Bachelor's & Master's"), ('all-levels', 'All levels')], max_length=30)),
                ('award_type', models.CharField(choices=[('merit', 'Merit-based'), ('need', 'Need-based'), ('special', 'Special category')], max_length=20)),
                ('applicant_type', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International'), ('domestic international', 'Domestic & International')], max_length=30)),
                ('award_tag_text', models.CharField(help_text='e.g. "Full Fee Waiver", "50% Tuition Discount"', max_length=100)),
                ('award_tag_color', models.CharField(choices=[('tag-gold', 'Gold'), ('tag-green', 'Green'), ('tag-purple', 'Purple')], default='tag-green', max_length=20)),
                ('award_tag_icon', models.CharField(choices=[('fas fa-trophy', 'Trophy'), ('fas fa-percent', 'Percent'), ('fas fa-hand-holding-usd', 'Hand holding USD')], default='fas fa-percent', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
