# Generated by Django 4.2.26 on 2026-02-21 16:45

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_scholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='description_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='description_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='excerpt_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='excerpt_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ru',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_uz',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_uz',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
