# Generated by Django 5.1.15 on 2026-04-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_jobposition_description_ru_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPosition',
        ),
    ]
