# Generated by Django 5.1.15 on 2026-02-17 10:13

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(blank=True, max_length=200)),
                ('name_ru', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('description_uz', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('description_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='departments/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_uz', models.CharField(blank=True, max_length=300)),
                ('title_ru', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('level', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('certificate', 'Certificate')], max_length=20)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('description_uz', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('description_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('duration', models.CharField(blank=True, help_text='e.g. "4 years"', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='programs/')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='programs.department')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
