# Generated by Django 4.2.26 on 2026-02-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_change_certificate_to_phd'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='program',
            name='study_type',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time')], default='full-time', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='tuition_fee',
            field=models.CharField(blank=True, help_text='e.g. "22,000,000 UZS"', max_length=100),
        ),
    ]
