# Generated by Django 5.1.15 on 2026-04-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_program_language_program_study_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='excerpt_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='excerpt_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.CharField(blank=True, choices=[('jurisprudence', 'Faculty of Jurisprudence'), ('business', 'Faculty of Business and Innovative Education')], help_text='Which faculty this department belongs to', max_length=50),
        ),
    ]
