# Generated by Django 5.1.15 on 2026-04-06 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_department_excerpt_department_excerpt_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='faculty',
            field=models.CharField(blank=True, choices=[('jurisprudence', 'Faculty of Jurisprudence'), ('business', 'Faculty of Business and Innovative Education')], max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='programs.department'),
        ),
    ]
